### ISSUE TITLE
captures returned rightmost-first, not leftmost-first as documented

### ISSUE THREAD

**Issue by anionic** [mndrix/regex#10]
Install "regex-0.3.1.zip" (12,015 bytes) Y/n?
true.

2 ?- use_module(library(regex)).
true.
3 ?- regex('(a+)(b+)', [], 'aabbb', Css).
Css = [[98, 98, 98], [97, 97]].

**Comment by mndrix** [comment]
Good catch.  All fixed.  Will be included in v0.3.2 shortly.
